# Generated by Django 5.1.4 on 2025-01-12 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'low'), ('normal', 'normal'), ('high', 'high'), ('urgent', 'urgent')], default='normal', max_length=15)),
                ('status', models.CharField(choices=[('not-started', 'Not started'), ('started', 'Started'), ('on-pause', 'On pause'), ('finished', 'Finished')], default='not-started', max_length=15)),
                ('deadline', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.CharField(max_length=50)),
            ],
        ),
    ]
